Attempting to create renderer
However, it refuses to compile because rustc thinks I'm violating some
borrow constraint.  However, I can't find where this is happening; let w
is taking *ownership* of the structure I'm letting be borrowed later, so
I'm at a total loss.

Here's the error.

kc5tja@enif:~/git/gemini$ cargo test
   Compiling gemini v0.1.0 (file:///home/kc5tja/git/gemini)
error[E0507]: cannot move out of borrowed content
  --> src/vdi.rs:97:42
   |
97 |         let r : render::Renderer = match (&w).renderer().index(0xFFFFFFFF).build() {
   |                                          ^^^^ cannot move out of borrowed content

error: aborting due to previous error

error[E0507]: cannot move out of borrowed content
  --> src/vdi.rs:97:42
   |
97 |         let r : render::Renderer = match (&w).renderer().index(0xFFFFFFFF).build() {
   |                                          ^^^^ cannot move out of borrowed content

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `gemini`.